### ISSUE TITLE
Path to template in error message

### ISSUE THREAD

**Issue by levkk** [rust-sailfish/sailfish#133]
Hello,

When I get an error inside a template, e.g. "cannot find value", the most common one for me when I forget to add a field into the template struct, the error message is not specific enough to which template this happens in:

```
  --> [...]/target/debug/build/sailfish-compiler-65715d21f8195176/out/templates/frame-0f5542b9bc5c4fd2:22:40
   |
22 |     __sf_rt::render_escaped!(__sf_buf, urls);
   |                                        ^^^^ help: a local variable with a similar name exists: `url
```

The error message only gives the name of the file, but what if I have more than one template named "frame"? This is common for "index", "get", "post" type templates that I would have in every folder in my MVC app.

I think the desired behavior here would be print the absolute path to the template file that was used to generate the rendered Rust file in which the actual error occurred.

**Comment by vthg2themax** [comment]
@levkk This seems like it would be pretty helpful to have. I can't promise this will be done quickly, but I'll look into this.

**Comment by vthg2themax** [comment]
@levkk It appears that this error message is actually produced by the Rust toolchain, so it is not something that appears to be able to be done. A workaround I use is to hold the CTRL key down in the error output window in VSCode, and go to the error causing file, which then includes a comment where the actual file is. Please see the following screenshots:
![image](https://github.com/rust-sailfish/sailfish/assets/25014503/55a6519d-bc3f-481d-bc02-fd3096764029)
![image](https://github.com/rust-sailfish/sailfish/assets/25014503/3d6a10f6-f302-4953-8a5b-20034e6e705d)
If anyone has any other ideas, I'm more than happy to amend my statement.

**Comment by vthg2themax** [comment]
@levkk I'm going to leave this open for a few weeks, and then if there's no changes, I'll close it, as I don't think this is something that can be modified with the current design.
