### ISSUE TITLE
Support optional feature for integration with axum

### ISSUE THREAD

**Issue by knarkzel** [rust-sailfish/sailfish#139]
I read this article today and it demonstrated how to make templates easier to use by implementing `IntoResponse` on a generic wrapper type: https://www.shuttle.rs/launchpad/issues/2023-10-17-issue-10-Serving-HTML

There should be an opt-in feature for enabling this integration for axum so that we can write following:

```rs
async fn hello(Path(name): Path<String>) -> impl IntoResponse {
    HelloTemplate { name }
}
```

Basically just implement this:

```rs
impl<T> IntoResponse for T
where
    T: Template,
{
    fn into_response(self) -> Response {
        match self.render() {
            Ok(html) => Html(html).into_response(),
            Err(err) => (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("Failed to render template. Error: {err}"),
            )
                .into_response(),
        }
    }
}
```

![image](https://github.com/rust-sailfish/sailfish/assets/85593302/717b5de2-4d15-4462-b62d-7304a248de4e)

**Comment by vthg2themax** [comment]
@PaulDotSH If you have some test coverage, and it doesn't introduce any breaking functionality changes, I'd be happy to review and accept your PR.

**Comment by vthg2themax** [comment]
@knarkzel @PaulDotSH Thank you very much for this, but I think that this project needs to keep its focus on simply being a templating engine in order for me to continue maintaining it. Thank you again @PaulDotSH for your wonderful contribution, and I hope you can turn it into a useful crate that will better help you in the future.
