### ISSUE TITLE
[BUG] Quotes in Tremplate are not rendered correctly ->`'` is rendered to `&amp;#039;`

### ISSUE THREAD

**Issue by Raboro** [rust-sailfish/sailfish#145]
I have a template for a github action. In this action I trigger a git commit via:

` git commit -am "<commit name>"`

But if I render no error occur, but it´s not correctly rendered:

`git commit -am &amp;#039;<commit name>&amp;#039;`

I tried to use `'` or `\'` in my String. But it´s still not generating the `'` character arround the commit message.

**Comment by PaulDotSH** [comment]
I cannot reproduce, both rendering `"` and `'` works perfectly fine for me, can you try to create a minimal reproducible example?

**Comment by PaulDotSH** [comment]
> Here is a example:
> 
> This is the template: `example.stpl`:
> 
> ```
> test: <%= text %>
> ```
> 
> The template struct:
> 
> ```rust
> #[derive(TemplateOnce)]
> #[template(path = "example.stpl")]
> pub struct Example<'a> {
>     pub text: &'a str,
> }
> ```
> 
> and the creation code of the template with print (in prod this would be written to a file):
> 
> ```rust
> let example = Example {
>     text: "git commit -am 'formatted and clippy'",
> };
> println!("{}", example.render_once().unwrap());
> ```
> 
> The console output is:
> 
> ```
> test: git commit -am &#039;formatted and clippy&#039;
> ```

This is expected behavior as <%= %> sanitizes the input, please try using <%- %> instead. note the - instead of the =

**Comment by Raboro** [comment]
thanks, it´s working now
