### ISSUE TITLE
Applying clippy lints

### ISSUE THREAD

**Issue by PaulDotSH** [rust-sailfish/sailfish#151]
Hi, I would like to implement the lints suggested by clippy, would that be accepted in a PR?
Most are extremely trivial and caused by the [auto-deref lint](https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref)
But there are many more, which would improve code readability IMO.

**Comment by vthg2themax** [comment]
@PaulDotSH Sure thing! A little housekeeping is always welcome. Thanks!
