### ISSUE TITLE
Minification "RFC"

### ISSUE THREAD

**Issue by PaulDotSH** [rust-sailfish/sailfish#153]
Hi, in the Axum support PR that wasn't accepted @vthg2themax mentioned something about a minify option, I would be open to implement it, however we should first check if it is ok, and if the api developed would be right with you.

First of all, since you don't want to add any dependencies, I was thinking of having something like

#[derive(TemplateOnce, Minify)]
#[sailfish(minify-with = "html-minifier")]
pub struct TestTemplate {
    pub short_id: String,
    pub full_id: String,
}

Having minify-with, could use some "hardcoded" commands like
html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true --input {file.stpl} --output {file_min.stpl}

Or if the user wants a custom minifying tool, they can use
#[sailfish(minify-with-command = "csso {INPUT} --output {OUTPUT}")]

Do you have any suggestions for the api or implementations? This way the user doesn't need to install anything else, but having binaries that are already installed will make minifying possible

**Comment by PaulDotSH** [comment]
Why I want to add this separately from just a feature, is because someone might use sailfish with html/css/js and non-web related technologies in the same project, and might want to run different binaries on said files

**Comment by PaulDotSH** [comment]
> In general I think minifaction and Axum support is a very valid use-case, but adding direct support for either in Sailfish makes the scope of the library grow and puts burden on @vthg2themax to maintain it. For Axum, it is a popular external crate that will undoubtedly circle back with requests to "upgrade Axum integration" once the Axum maintainers release breaking changes. For external binary calls like html-minifier it is the same, but worse as installed versions of these binaries will differ much more between users.
> 
> Neither Axum nor HTML minification _needs_ Sailfish support, using the NewType pattern with a generic type, supporting both Axum and minification can be done (untested, rough sketch);
> 
> ```rust
> struct Minified<T>(T);
> 
> impl<T: TemplateOnce> Minified<T> {
>     fn render_and_minify(self) -> String {
>         let rendered = self.0.render_once().unwrap();
>         minify_html(rendered) // Use whatever library/cli you want
>     }
> }
> 
> // Adds MyTemplate.into() method
> impl<T: TemplateOnce> From<T> for Minified<T> {
>     fn from(other: T) -> Self {
>         Self(other)
>     }
> }
> 
> // Axum integration
> impl<T: TemplateOnce> IntoResponse for Minified<T> {
>     fn into_response(self) -> Response {
>         Response::builder()
>             .header("Content-Type", "text/html; charset=utf-8")
>             .status(StatusCode::OK)
>             .body(self.render_and_minify())
>     }
> }
> ```
> 
> This `Minified<T>` will work for any Sailfish template and provides both minification and Axum integration, and can be easily adapted to only support either. In your Axum handlers you only need to return the `Minified<MyTemplate>`
> 
> ```rust
> #[derive(TemplateOnce)]
> #[template(path = "hello.stpl")]
> struct HelloTemplate(String);
> 
> async fn hello(Path(name): Path<String>) -> Minified<HelloTemplate> {
>     HelloTemplate(name).into()
> }
> ```
> 
> This can of course be released as a standalone crate, e.g `axum-sailfish` (or `sailfish-extras` that supports many external crates via feature flags) if someone wants to maintain it outside of the Sailfish crate.
> 
> Adding direct support for minification in Sailfish should in my opinion not require any external crates/binaries and should instead be done at template compile-time by stripping newlines and whitespace at template parse-time similar to the `rm_whitespace` [derive option](https://rust-sailfish.github.io/sailfish/options/#derive-options).

Thank you for the insight, the only thing is that I think you'd first want to minify the template and then compile it, since it doesn't need to be minified every time you send it to the user.

I have only one question left, would you and @vthg2themax consider it ok if I released something like sailfish-minify then?
And thank you again for your concise response

**Comment by vthg2themax** [comment]
@PaulDotSH I think releasing the minification feature as another crate would be fantastic with a name like `sailfish-minify`. I can even put a link to it in the documentation, or something if you'd like. I know for my use cases, I'd like to minify my templates, but I've just been manually doing that with external tools before deploying.

@Svenskunganka Thank you as well for your excellent ideas, and I appreciate the wisdom you've shared!

**Comment by PaulDotSH** [comment]
@vthg2themax sorry for the @, but I would like to request feedback if/when you have time, for the crate

https://crates.io/crates/sailfish-minify

**Comment by vthg2themax** [comment]
@PaulDotSH I think it looks good so far. Very succinct syntax!

Just a note, but there is a breaking change coming ahead with the 0.9.0-beta branch that basically means you need to change `TemplateOnce` to `TemplateSimple` to keep your functionality intact, so I wanted to give you a heads up on that. I will be leaving it up for a week for people to test it out, and then if no one has any objections, I will promote it. Hopefully it doesn't make your crate need too many changes.

**Comment by PaulDotSH** [comment]
> @PaulDotSH I think it looks good so far. Very succinct syntax!
> 
> Just a note, but there is a breaking change coming ahead with the 0.9.0-beta branch that basically means you need to change `TemplateOnce` to `TemplateSimple` to keep your functionality intact, so I wanted to give you a heads up on that. I will be leaving it up for a week for people to test it out, and then if no one has any objections, I will promote it. Hopefully it doesn't make your crate need too many changes.

Thank you very much for the heads up.
I cannot find the code for sailfish 0.9.0-beta, is it not on this repo yet? Since just replacing TemplateOnce with TemplateSimple doesnt seem to work, and I would probably need to check the source code

**Comment by vthg2themax** [comment]
@PaulDotSH Rats, I didn't push the branch. I'll get to it tonight, and let you know.

**Comment by PaulDotSH** [comment]
> @PaulDotSH Rats, I didn't push the branch. I'll get to it tonight, and let you know.

No hurry, thank you for maintaining this crate and for all the help and support

**Comment by vthg2themax** [comment]
@PaulDotSH The latest changes have been pushed to the main branch.
