### ISSUE TITLE
Fixing CI/CD tests

### ISSUE THREAD

**Issue by PaulDotSH** [rust-sailfish/sailfish#154]
Hi, is there an interest into fixing the CI/CD tests? Since my last pr merged, I got notified that some tests failed, and I saw that some have outdated dependencies, would it be ok if I opened a PR to fix the tests?

**Comment by vthg2themax** [comment]
Absolutely! Thank you very much! I ran out of time this weekend to do much else, but I was going to put that on my to do list for the future.
