### ISSUE TITLE
RFC 3: Template trait

### ISSUE THREAD

**Issue by Kogia-sima** [rust-sailfish/sailfish#3]
## Description

`Template` trait has method `render()` which does not consume the object itself.

[Rendered](https://github.com/Kogia-sima/sailfish/blob/master/docs/rfcs/3-template-trait.md)

**Comment by mibmo** [comment]
Any updates on this?
Is the crate still being maintained?

**Comment by SciStarter** [comment]
This is implemented as of release 0.9.0
