### ISSUE TITLE
Undefined behaviour detected by Miri

### ISSUE THREAD

**Issue by ssokolow** [rust-sailfish/sailfish#38]
Given that the state of the art for automatically detecting problems with `unsafe` has progressed since I opened bug #26, I decided to do a cursory run of `MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly miri test` on Sailfish... and the result [wasn't good](https://gist.github.com/ssokolow/82931498e886e350981bac2189e42500).

```
test read_config ... error: Undefined Behavior: type validation failed: encountered uninitialized bytes at .<enum-tag>, but expected a valid enum tag
   --> /home/ssokolow/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.3/src/lib.rs:114:16
    |
114 |     let Node { key, value, .. } = *Box::from_raw(the_box);
    |                ^^^ type validation failed: encountered uninitialized bytes at .<enum-tag>, but expected a valid enum tag
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
            
    = note: inside `linked_hash_map::drop_empty_node::<yaml_rust::yaml::Yaml, yaml_rust::yaml::Yaml>` at /home/ssokolow/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.3/src/lib.rs:114:16
    = note: inside `<linked_hash_map::LinkedHashMap<yaml_rust::yaml::Yaml, yaml_rust::yaml::Yaml> as std::iter::IntoIterator>::into_iter` at /home/ssokolow/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.3/src/lib.rs:1134:22
    = note: inside `sailfish_compiler::config::imp::ConfigFile::visit_global` at /home/ssokolow/tmp/sailfish/sailfish-compiler/src/config.rs:115:27
    = note: inside `sailfish_compiler::config::imp::ConfigFile::read_from_file` at /home/ssokolow/tmp/sailfish/sailfish-compiler/src/config.rs:104:17
    = note: inside `sailfish_compiler::config::imp::<impl sailfish_compiler::Config>::search_file_and_read` at /home/ssokolow/tmp/sailfish/sailfish-compiler/src/config.rs:48:25
```

(`miri 0.1.0 (2065b52 2020-12-11)`, run against 1128fda3d327307bd414b3cbc7d4af1fa668f91f)

If you're not familiar with [Miri](https://github.com/rust-lang/miri), it's the compile-time execution engine used for Rust's `const fn`s, adapted to work like LLVM's sanitizers or Valgrind but for undefined behaviour.

After fixing that, I strongly recommend making sure you have all your uses of `unsafe` exercised by tests and then re-running Miri. It can't catch everything, but it's something I'd now consider essential for use of `unsafe`.

The Miri README also has [instructions](https://github.com/rust-lang/miri#running-miri-on-ci) for running it as part of your CI testing.

**Comment by Kogia-sima** [comment]
@ssokolow Thanks for your investigation.

It is `sailfish-compiler` crate that depends on `linked-hash-map` crate. `sailfish` crate does not depends on it (although `sailfish` indirectly depends on `sailfish-macros` which depends on `sailfish-compiler`, `sailfish` just re-exports the derived macros defined in `sailfish-macros`).

And `sailfish-compiler` crate is marked with `#![forbid(unsafe_code)]`, which means `sailfish-compiler` crate does not contain any `unsafe` block. I suspect that this is a bug inside the `linked-hash-map` crate.

Btw `sailfish` crate is tested by miri on the GitHub Actions (https://github.com/Kogia-sima/sailfish/runs/1604114236?check_suite_focus=true)

**Comment by ssokolow** [comment]
Getting familiar with GitHub Actions is still on my TODO list so I'll admit I had a stupid moment where I couldn't figure out how your tests were getting invoked now that you're no longer on third-party CI and didn't check for Miri in them.

As for having it in the compiler, that *is* a bit better but you can never let your guard down with undefined behaviour. Who knows how easily UB in the compiler could result in it neglecting to emit a safety check in the compiled output.

**Comment by Kogia-sima** [comment]
Possibly related to https://github.com/chyh1990/yaml-rust/issues/167

**Comment by Kogia-sima** [comment]
I tested `linked-hash-map` crate under miri and encountered a similar error message.

```console
     Running target/x86_64-unknown-linux-gnu/debug/deps/heapsize-b4ec5f242f183ccd

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-gnu/debug/deps/serde-3a8c60f6fa532154

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/x86_64-unknown-linux-gnu/debug/deps/test-cd7afc96213a7352

running 19 tests
test entries_insert ... ok
test test_borrow ... error: Undefined Behavior: type validation failed: encountered uninitialized reference
   --> /home/kogia-sima/PG/Rust/3rdparty/linked-hash-map/src/lib.rs:114:21
    |
114 |     let Node { key, value, .. } = *Box::from_raw(the_box);
    |                     ^^^^^ type validation failed: encountered uninitialized reference
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information

    = note: inside `linked_hash_map::drop_empty_node::<test_borrow::Foo, &str>` at /home/kogia-sima/PG/Rust/3rdparty/linked-hash-map/src/lib.rs:114:21
    = note: inside `<linked_hash_map::LinkedHashMap<test_borrow::Foo, &str> as std::ops::Drop>::drop` at /home/kogia-sima/PG/Rust/3rdparty/linked-hash-map/src/lib.rs:809:17
    = note: inside `std::intrinsics::drop_in_place::<linked_hash_map::LinkedHashMap<test_borrow::Foo, &str>> - shim(Some(linked_hash_map::LinkedHashMap<test_borrow::Foo, &str>))` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:179:1
note: inside `test_borrow` at tests/test.rs:414:1
   --> tests/test.rs:414:1
    |
414 | }
    | ^
note: inside closure at tests/test.rs:373:1
   --> tests/test.rs:373:1
    |
373 | / fn test_borrow() {
374 | |     #[derive(PartialEq, Eq, Hash)] struct Foo(Bar);
375 | |     #[derive(PartialEq, Eq, Hash)] struct Bar(i32);
376 | |
...   |
413 | |     assert_eq!(map.remove(&Foo(Bar(2))), None);
414 | | }
    | |_^
    = note: inside `<[closure@tests/test.rs:373:1: 414:2] as std::ops::FnOnce<()>>::call_once - shim` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
    = note: inside `<fn() as std::ops::FnOnce<()>>::call_once - shim(fn())` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
    = note: inside `test::__rust_begin_short_backtrace::<fn()>` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:516:5
    = note: inside closure at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:507:30
    = note: inside `<[closure@test::run_test::{closure#2}] as std::ops::FnOnce<()>>::call_once - shim(vtable)` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
    = note: inside `<std::boxed::Box<dyn std::ops::FnOnce() + std::marker::Send> as std::ops::FnOnce<()>>::call_once` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1328:9
    = note: inside `<std::panic::AssertUnwindSafe<std::boxed::Box<dyn std::ops::FnOnce() + std::marker::Send>> as std::ops::FnOnce<()>>::call_once` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:322:9
    = note: inside `std::panicking::try::do_call::<std::panic::AssertUnwindSafe<std::boxed::Box<dyn std::ops::FnOnce() + std::marker::Send>>, ()>` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
    = note: inside `std::panicking::try::<(), std::panic::AssertUnwindSafe<std::boxed::Box<dyn std::ops::FnOnce() + std::marker::Send>>>` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
    = note: inside `std::panic::catch_unwind::<std::panic::AssertUnwindSafe<std::boxed::Box<dyn std::ops::FnOnce() + std::marker::Send>>, ()>` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:396:14
    = note: inside `test::run_test_in_process` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:538:18
    = note: inside closure at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:449:39
    = note: inside `test::run_test::run_test_inner` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:474:13
    = note: inside `test::run_test` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:504:28
    = note: inside `test::run_tests::<[closure@test::run_tests_console::{closure#2}]>` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:283:13
    = note: inside `test::run_tests_console` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/console.rs:289:5
    = note: inside `test::test_main` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:121:15
    = note: inside `test::test_main_static` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/lib.rs:140:5
    = note: inside `main`
    = note: inside `<fn() as std::ops::FnOnce<()>>::call_once - shim(fn())` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
    = note: inside `std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
    = note: inside closure at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
    = note: inside `std::ops::function::impls::<impl std::ops::FnOnce<()> for &dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe>::call_once` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:259:13
    = note: inside `std::panicking::try::do_call::<&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe, i32>` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
    = note: inside `std::panicking::try::<i32, &dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe>` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
    = note: inside `std::panic::catch_unwind::<&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe, i32>` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:396:14
    = note: inside `std::rt::lang_start_internal` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:51:25
    = note: inside `std::rt::lang_start::<()>` at /home/kogia-sima/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
    = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: test failed, to rerun pass '--test test'
```

Now I've opened a [bug report](https://github.com/contain-rs/linked-hash-map/issues/104) in `linked-hash-map` repository

**Comment by Svenskunganka** [comment]
It seems maintenance has unfortunately stagnated for both the `rust_yaml` and `linked_hash_map` crates.

@Kogia-sima was there any particular reason you decided upon YAML rather than the more "rusty" TOML for configuration files? If not, would you consider accepting a PR migrating from YAML to TOML using https://github.com/alexcrichton/toml-rs?  
I suspect both `serde` and `toml` would have to be added to `sailfish-compiler` dependencies, although `serde` is already a required dependency of `toml` and also used in the main `sailfish` crate - so total number of dependencies of this project would remain unchanged.

Since it's a breaking change, I want to check with you before I begin if you think this issue warrants that, or if you'd rather wait and see if `rust_yaml` and `linked_hash_map` crates gets patched.

**Comment by Kogia-sima** [comment]
@Svenskunganka It seems that there is already [PR](https://github.com/chyh1990/yaml-rust/pull/157) to fix this issue, but author does not have any contribute since June.

> was there any particular reason you decided upon YAML rather than the more "rusty" TOML for configuration files?

Because YAML syntax is simple and suitable for small configurations. TOML requires all keys to be wrapped in scope. However I think it's better to solve this issue rather than stick the YAML format.

> Since it's a breaking change, I want to check with you before I begin if you think this issue warrants that, or if you'd rather wait and see if rust_yaml and linked_hash_map crates gets patched.

I will be happy if you changes the configuration format used in this crate and solve this issue. Thank you for all discussion and your work.

**Comment by Svenskunganka** [comment]
> Because YAML syntax is simple and suitable for small configurations. TOML requires all keys to be wrapped in scope. However I think it's better to solve this issue rather than stick to the YAML format.

I understand, thank you for clarifying! I'm unsure what you mean with *"TOML requires all keys to be wrapped in scope"*. If I understand the spec correctly, the equivalent YAML and TOML configuration files for Sailfish would look like:

YAML:
```yaml
template_dir: "templates"
escape: true
delimiter: "%"

optimization:
    rm_whitespace: false
```

TOML:
```toml
template_dir = "templates"
escape = true
delimiter = "%"

[optimization]
rm_whitespace = false
```

> I will be happy if you make changes in the configuration format used in this crate and solve this issue.

Is TOML ok or do you have any other format you'd prefer?

> Thank you for all discussion and your work.

Thank you as well for all your work on Sailfish! It's a lovely piece of software and in my experience the most ergonomic compiled template engine for Rust.  
I'm still fairly new to Rust but feel free to @me whenever a simpler issue pops up or if you want help/input in documentation-related issues - I'm happy to help where and when I can.

**Comment by Kogia-sima** [comment]
> I'm unsure what you mean with "TOML requires all keys to be wrapped in scope".

Sorry I misunderstood that. I just thought that you must wrap all keys in some scope like this:

```toml
[global]
key1 = "..."

[private]
key2 = "..."
```

> Is TOML ok or do you have any other format you'd prefer?

That's ok. I know TOML is very common style of configuration format, and particularly familiar with Rust programmers. Ideally I would like to rename `template_dir` to `template_dirs`, and accept value as an array by default.

```toml
template_dirs = ["templates"]
escape = true
delimiter = "%"

[optimization]
rm_whitespace = false
```

**Comment by Kogia-sima** [comment]
> I'm still fairly new to Rust but feel free to @ me whenever a simpler issue pops up or if you want help/input in documentation-related issues - I'm happy to help where and when I can.

I'm happy to hear that! Since english is not my first language, writing documents is hard task for me. Feel free to create a PR if you found any grammatical mistakes or typo.

**Comment by Svenskunganka** [comment]
The PR bumps `yaml-rust` to `0.4.5` which fixes the immediate issue here. This issue is therefore no longer a breaking change. Perhaps we should break the YAML to TOML migration out into a separate issue marked as breaking and put on the 0.4.0 todo list rather than this one. I'll keep `template_dir` to `template_dirs` change as well as #42 in mind for that implementation.

**Comment by Kogia-sima** [comment]
Closing in favor of #44
