### ISSUE TITLE
Rust Analyzer in VS Code doesn't use sailfish.yml

### ISSUE THREAD

**Issue by montanalow** [rust-sailfish/sailfish#65]
When using non-default settings in `sailfish.yml` e.g. `template_dir: ./src/templates` Rust Analyzer gives a macro-error message "failed to load file ...". Is there additional configuration available to help Rust Analyzer find the correct `template_dir` when it tries to expand the `template(path = ...)` macro?

**Comment by vthg2themax** [comment]
@montanalow The sailfish.yml has been changed to a TOML now. Please let me know if this issue still exists. If there is no response in a week, this issue will be closed. Feel free to open a new issue if you don't have time to respond.

**Comment by Kogia-sima** [comment]
Closing as stale.
