### ISSUE TITLE
Can't compile the project with only one dependency sailfish="0.3.3"

### ISSUE THREAD

**Issue by opuzyr** [rust-sailfish/sailfish#67]
Created a new project, added the dependency and compiler fails. Could you please suggest how to fix that?

**rustc 1.57.0 (f1edd0429 2021-11-29)**
 
**Cargo.toml**
[package]
name = "testapp"
version = "0.1.0"
edition = "2021"

[dependencies]
sailfish = "0.3.3"

**Output:**

error[E0599]: no function or associated item named `from_str_unchecked` found for struct `proc_macro2::Literal` in the current scope
   --> /Users/opuzyr/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.11/src/runtime.rs:301:41
    |
301 |         let literal = unsafe { Literal::from_str_unchecked(repr) };
    |                                         ^^^^^^^^^^^^^^^^^^ function or associated item not found in `proc_macro2::Literal`

**Comment by Svenskunganka** [comment]
Related to dtolnay/quote#204

Does it compile if you add this to your dependencies:

```toml
[dependencies]
quote = "=1.0.10"
```

**Comment by vthg2themax** [comment]
Looks like this issue is resolved! Please let me know if otherwise.
