### ISSUE TITLE
Is sailfish still maintained?

### ISSUE THREAD

**Issue by jdrouet** [rust-sailfish/sailfish#70]
Hi everyone!
Sailfish is currently blocking the `proc-macro2` dependency to an old version.
Some people (including me) proposed some PRs (#60, #61, #68) to fix this issue, without breaking the tests in place.
There was no update on the main branch this April 2021.
Should we consider this project not to be maintained anymore? Could we help you find a maintainer to deal with it?
Your project is nice, performant, seems well tested, that would be a shame to lose it...

**Comment by fakeshadow** [comment]
@Kogia-sima I'd like to ask the same question. Please let us know what we can do to help to keep this project going.

**Comment by vthg2themax** [comment]
Is there a fork out there that can be used instead of this version?

**Comment by vthg2themax** [comment]
I uploaded a version to Crates.io with the changes to cargo.toml that were proposed. Please let me know if you want me to take mine down. I just want to preserve this excellent library for use.
https://crates.io/crates/black_marlin

**Comment by Svenskunganka** [comment]
@vthg2themax if you're running into the issue described in #67, you can use any of the PRs that updates the `proc-macro2` dependency:

```toml
[dependencies]
sailfish = { git = "https://github.com/Kogia-sima/sailfish", rev = "refs/pull/XX/head" }
```
where `XX` is the pull request number, all of the following pull requests updates the `proc-macro2` dependency: #60, #61, #68, #69, #71 so you can choose whichever one you like, e.g `rev = "refs/pull/71/head"`.

Alternatively, use the fix I mentioned in https://github.com/Kogia-sima/sailfish/issues/67#issuecomment-1003095982 which however may collide with your other dependencies.

----

If you're looking for an actively maintained fork, there isn't any. I have a PR that fixes a couple of issues over in #57, but it has the same issue as upstream with `proc-macro2` version and hasn't been reviewed yet. It's also a breaking change.

**Comment by vthg2themax** [comment]
@Svenskunganka Well, I am not an expert by any means on this library, but I wanted to offer an easy way to allow this project to evolve going forward. On my version, I used the https://github.com/Kogia-sima/sailfish/pull/71 request which updated the version number. I also renamed a few files, and will need to make sure that there is some other changes made in order to ensure that the library can go on in case I no longer want to support this project.

**Comment by jdrouet** [comment]
Did anyone try to contact @Kogia-sima with his email address?

**Comment by jdrouet** [comment]
I did send this person an email, no answer for now.

**Comment by vthg2themax** [comment]
@Svenskunganka, @jdrouet, @fakeshadow , @Kogia-sima , I will continue to maintain my fork with any pull requests, and upon notification that I should take it down, I will. I just want to use a library that is friendly to novices to pickup without needing to know about special branch commands. @Svenskunganka  Thank you very much by the way for that wonderful insight though!

**Comment by Kogia-sima** [comment]
@Svenskunganka, @jdrouet, @fakeshadow , @vthg2themax I'm very sorry for taking long time to response. I'm so working hard now that I can't resume development soon. If someone is passionate about developing this crate, I'll transfer the ownership of this repository. Otherwise, I'm planning to automatically update the dependencies using GitHub Actions, but won't implement any new feature any more. Please let me know if you are willing to continue this project.

**Comment by jdrouet** [comment]
@Kogia-sima maybe you can give write access to some of us and we'll try to upgrade your repo as we can. Or move it to an organization? 😉
Would be great also to have access to crates.io to be able to publish a new version 😉

**Comment by Kogia-sima** [comment]
@jdrouet Of course there are many other options but for now, I'm planning to solve the current issue by transferring repository permissions. I'll leave it to the new owner to decide what to do after that.

**Comment by vthg2themax** [comment]
Thank you very much for responding @Kogia-sima ! If no one else has any objections, I would be willing to step forward to maintain this. I would also be willing to work to get this moved to an organization. Does anyone have any recommendations for organizations I should contact first?

**Comment by Kogia-sima** [comment]
@vthg2themax That's very nice of you!!! If you want to work on an organization I think you should create a new organization by yourself.

I'm going to wait for an another candidate until Feb 19, 2022, at 9:00 a.m. (JST). If no other candidates appear I'll transfer the ownership of repository to @vthg2themax. Thank you for your understanding.

**Comment by Kogia-sima** [comment]
Note that some contents depend on my gist. I might apply some changes to sailfish in order to make transmission easy.

**Comment by jdrouet** [comment]
@vthg2themax if you need anybody with you in the organization, I'd love to be part of it!

**Comment by Kogia-sima** [comment]
It seems @vthg2themax and @jdrouet are both willing to continue the project. I invited you to a organization.

**Comment by vthg2themax** [comment]
Sounds great @Kogia-sima ! I will do my best by this project!

**Comment by Kogia-sima** [comment]
@Svenskunganka, @jdrouet, @fakeshadow, and @vthg2themax I'm sorry for long time stagnation. Now the repository has been completely transferred. I appreciate all of your kind.
