### ISSUE TITLE
vscode extension end tag red color

### ISSUE THREAD

**Issue by dvic** [rust-sailfish/sailfish#86]
Any idea why the end tags are red coloured? Is anyone else experiencing this? I tried resetting my vscode settings but it's still red, is it a bug or something else?

<img width="351" alt="image" src="https://user-images.githubusercontent.com/1214337/168427302-dfbcd804-825e-44c8-aace-22334b480ad0.png">

**Comment by vthg2themax** [comment]
@dvic  My tags are red too at the end. I am not too familiar with the vscode plugin, but I would imagine that a change to that could affect this behavior. What do you think would be a helpful change, if not to be red?

**Comment by dvic** [comment]
I guess the start tag should also be red then? (like in the readme)

**Comment by vthg2themax** [comment]
@dvic Please see the latest updated extension. It also adds formatting the document.
