### ISSUE TITLE
error trying to use sailfish

### ISSUE THREAD

**Issue by jhjacobs81** [rust-sailfish/sailfish#98]
hello!

when i try to include the latest version of sailfish (the one i get using cargo add sailfish) my app wont compile with the following error(s):
```error: failed to select a version for `proc-macro2`.
    ... required by package `sailfish-compiler v0.4.0`
    ... which satisfies dependency `sailfish-compiler = "^0.4.0"` of package `sailfish-macros v0.4.0`
    ... which satisfies dependency `sailfish-macros = "^0.4.0"` of package `sailfish v0.4.0`
    ... which satisfies dependency `sailfish = "^0.4.0"` of package `aviacms v0.1.0 (/home/sysop/Rust/01-aviacms)`
versions that meet the requirements `>=1.0.11, <=1.0.36` are: 1.0.36, 1.0.35, 1.0.34, 1.0.33, 1.0.32, 1.0.31, 1.0.30, 1.0.29, 1.0.28, 1.0.27, 1.0.26, 1.0.25, 1.0.24, 1.0.23, 1.0.22, 1.0.21, 1.0.20, 1.0.19, 1.0.18, 1.0.17, 1.0.16, 1.0.15, 1.0.14, 1.0.13, 1.0.12

all possible versions conflict with previously selected packages.

  previously selected package `proc-macro2 v1.0.37`
    ... which satisfies dependency `proc-macro2 = "^1.0.37"` of package `darling_core v0.14.1`
    ... which satisfies dependency `darling_core = "=0.14.1"` of package `darling v0.14.1`
    ... which satisfies dependency `darling = "^0.14.1"` of package `salvo_macros v0.29.0`
    ... which satisfies dependency `salvo_macros = "^0.29.0"` of package `salvo_core v0.29.0`
    ... which satisfies dependency `salvo_core = "^0.29.0"` of package `salvo v0.29.0`
    ... which satisfies dependency `salvo = "^0.29.0"` of package `aviacms v0.1.0 (/home/sysop/Rust/01-aviacms)`

failed to select a version for `proc-macro2` which could resolve this conflict```

i am very new to both Rust and Sailfish, and i could use some help and guidance :)

**Comment by vthg2themax** [comment]
@apps4uco Thank you very much for helping out with this!
@jhjacobs81 are you still experiencing any issues with this?

**Comment by jhjacobs81** [comment]
i have since moved on to other templating. But im not really happy about it atm, so give me a few days..

**Comment by vthg2themax** [comment]
Alrighty, since this doesn't seem to still be an issue, I will close this then. Please let me know if this needs to be revived.
